// SPDX-FileCopyrightText: 2026 Latere AI
// SPDX-License-Identifier: MIT

// Command rules is the alert table of spec 018 in two shapes.
//
// Without a flag it prints the plain Prometheus rules document on standard
// output, which is what `promtool check rules` parses: promtool reads a rules
// file and not a Kubernetes object, and the rules job of verify.yml pipes
// this into it.
//
//	go run ./tools/rules > out/rules.yaml && promtool check rules out/rules.yaml
//
// With -write it writes deploy/base/prometheusrule.yaml, the PrometheusRule
// an installation running the Prometheus operator applies beside the base.
// Run it from the repository root, which `make rules` does, and commit the
// result: a test here fails when the committed file is not what a fresh run
// produces, so an alert edited in one of the two places does not reach main.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Path is where the manifest is committed, relative to the repository root.
var Path = filepath.Join("deploy", "base", "prometheusrule.yaml")

func main() { os.Exit(cli(os.Args[1:], os.Stdout, os.Stderr)) }

// cli prints the rules document, or writes the manifest under the working
// directory, and answers the process exit code: 0 on success, 1 with one line
// on stderr otherwise, 2 on a bad flag.
func cli(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("rules", flag.ContinueOnError)
	fs.SetOutput(stderr)
	write := fs.Bool("write", false, "write "+Path+" instead of printing the rules document")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if !*write {
		_, _ = io.WriteString(stdout, Document())
		return 0
	}
	if err := os.WriteFile(Path, Render(), 0o644); err != nil {
		_, _ = fmt.Fprintf(stderr, "rules: %v\n", err)
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "rules: wrote %s\n", Path)
	return 0
}

// preamble is the manifest's header: why the file sits beside the base's
// kustomization rather than in it, and how an installation applies it. It is
// part of the rendering, because the file an operator opens is the file this
// tool writes and a comment that lived only in git would be lost on the first
// regeneration.
const preamble = `# SPDX-FileCopyrightText: 2026 Latere AI
# SPDX-License-Identifier: MIT

# The alerts of spec 018, one rule per row of that spec's table.
#
# Generated by tools/rules. Edit the table there and run ` + "`make rules`" + `; a test
# fails when this file is not what a fresh run produces, and a second test
# fails when an alert names an arca_ metric or a label internal/metrics does
# not register.
#
# This object needs the Prometheus operator's CustomResourceDefinition. Arca
# does not require the operator and the kind example does not install it, so
# deploy/base/kustomization.yaml does not name this file: a base that did
# would fail to apply on every installation without the operator. An
# installation that runs it applies this file beside the base:
#
#   kubectl apply -n <namespace> -f deploy/base/prometheusrule.yaml
#
# The last two alerts are the only ones over metrics Arca does not export.
# kube-state-metrics publishes the Pod conditions and the autoscaler's replica
# counts, and an installation without it does not fire them.
`

// Render is the committed manifest's bytes: the preamble, the object, and
// the rules document indented into its spec.
func Render() []byte {
	var b strings.Builder
	b.WriteString(preamble)
	b.WriteString("apiVersion: monitoring.coreos.com/v1\n")
	b.WriteString("kind: PrometheusRule\n")
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: %s\n", Group)
	b.WriteString("  labels:\n")
	fmt.Fprintf(&b, "    app.kubernetes.io/name: %s\n", Group)
	b.WriteString("spec:\n")
	b.WriteString(indent(Document()))
	return []byte(b.String())
}

// indent puts the rules document under spec:, two spaces in, which is the
// shape the reader in the other direction relies on: removing that indent
// from everything under spec: leaves the document promtool expects.
func indent(document string) string {
	var b strings.Builder
	for line := range strings.SplitSeq(strings.TrimRight(document, "\n"), "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("  " + line + "\n")
	}
	return b.String()
}
